#ifndef TEMPLATEPLUGIN_GLOBAL_H
#define TEMPLATEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLATEPLUGIN_LIBRARY)
#  define TEMPLATEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPLATEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATEPLUGIN_GLOBAL_H
