#ifndef COPYMAKEBORDERPLUGIN_GLOBAL_H
#define COPYMAKEBORDERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COPYMAKEBORDERPLUGIN_LIBRARY)
#  define COPYMAKEBORDERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COPYMAKEBORDERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COPYMAKEBORDERPLUGIN_GLOBAL_H
